# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: aimpointllconline.com
title: AimPoin LLC
email: smbergstedt@aimpointllconline.com
author: Sylvia Bergstedt
description: > #Firearms training for everyone.
copyright: 'Copyright &copy; 2016 AimPoint LLC. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Email Us
    url: mailto:smbergstedt@aimpointllconline.com

